### ISSUE TITLE
Proposal: Ensure the operator always builds with 2nd last release of the recent Go version

### ISSUE THREAD

**Issue by baijum** [servicebinding/service-binding-controller#97]
I propose to ensure the operator always builds with 2nd last release of the recent Go version. For example, the current version of Go is Go 1.18.x. At this time, the operator build should work with Go 1.16.x. This is going to help downstream vendors to package the operators and distribute without changing the Go toolchain. As of today, Red Hat's [Go toolchain version is Go 1.16](https://catalog.redhat.com/software/containers/rhel8/go-toolset/5b9c810add19c70b45cbd666).

This requirement doesn't prevent upgrading the version of Go.  But the operator cannot use any recent language changes and standard library changes.

**Comment by scothis** [comment]
I don't think that a good idea. Go 1.16 is EOL. I'm comfortable with staying off the bleeding edge of new releases (e.g. `x.x.0`, `x.x.1`), but we shouldn't be afraid to track the latest "stable".

There are plenty of examples of other oss projects that use newer versions of go that RedHat contributes to and productizes. For example, Kubernetes and Knative.

**Comment by baijum** [comment]
Based on the discussion at the community call, I am closing this issue.
